default: &default
  adapter: sqlite3

development:
  <<: *default
  database: db/development.sqlite

test:
  <<: *default
  database: db/test.sqlite

production:
  <<: *default
  database: db/production.sqlite
